[project]
name = "repomind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Amitesh Pandey", email = "amiteshpandey7050@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
repomind = "repomind:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
